Fix compilation with libdrm-2.4.130
Fix error: redefinition of 'struct drm_color_ctm_3x4'.

drm_color_ctm_3x4 structure is now defined in https://github.com/torvalds/linux/commit/e5719e7f19009d4fbedf685fc22eec9cd8de154f#diff-4c51fb416ec7cc69566cd7b795ee57eb070aa1006ad65d6962081f039ffb2718

As this structure is unused and not a part of amdsmi public interface,
it is safe to remove it.